sudo: required
services:
  - docker

before_install:
  - docker build -t adi1916/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adi1916/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "EBS_Docker"
  env: "EBSDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-685855047331"
  bucket_path: "EBS_Docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
